Process data
jsug9/blog-app pull request #2
Opened 2022-07-06 19:42 UTC by jsug9

### Hello 👋 
**In this project:**

**Use models to insert data**
- Create at least one user by running the following code:
    ```ruby
       first_user = User.create(name: 'Tom', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Mexico.')
    ```
- Create at least 4 posts written by one of the users you created by running the following code:
    ```ruby
       first_post = Post.create(author: first_user, title: 'Hello', text: 'This is my first post')
    ```
- Create at least 6 posts comments for one of the posts you created by running the following code:
    ```ruby
       Comment.create(post: first_post, author: second_user, text: 'Hi Tom!' )
    ```
- Use other [CRUD methods](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/lessons/active_record_crud.md) to find, update and delete entities.

**Create custom methods**
- A method that returns the 3 most recent posts for a given user.
- A method that updates the posts counter for a user.
- A method which returns the 5 most recent comments for a given post.
- A method that updates the comments counter for a post.
- A method that updates the likes counter for a post.

2022-07-06 21:02 UTC, Gambit142 requested changes
Hi @jsug9 👋, 

Good job so far!

## Highlights
- Defined models properly ✔️ 
- Set up associations between models properly ✔️ 
- Defined required methods in each model ✔️ 

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
#### I am making this comment here because I can't highlight the `README.md` file in files changed section of this pull request.

- [ ] Kindly include instructions for running this repository locally after cloning in the `README.md` file. You can take a cue from the following instructions:

```readme.md
check the ruby version being used and install it if it is not the same with that of the local machine
set up database direct them to the config/database.yml file
run 'bundle install'
run 'npm install' or 'yarn install'
run 'rails db:create'
run rails 'db:migrate'
run rails 'db:seed' if there is data in the seed
run 'rails s' to start the server locally
```

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Kindly consider the optional suggestions under this review summary. I highly recommend that you implement them so that you can achieve other milestones easily. 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-07-06 21:02 UTC, Gambit142 commented on app/models/comment.rb
> +  end
- [x] [Optional] It would be nice to make this a private method and then, you use the Rails Active Callback method after_save to automatically call the method. If you decide to implement it, it would be like this:

```ruby on rails
...

after_save :update_comments_counter

private

def update_comments_counter
   post.update(comments_counter: post.comments.count)
end
```

2022-07-06 21:02 UTC, Gambit142 commented on app/models/like.rb
> +  end
- [x] [Optional] It would be nice to make this a private method and then, you use the Rails Active Callback method after_save to automatically call the method. If you decide to implement it, it would be like this:

```ruby on rails
...

after_save :update_likes_counter

private

def update_likes_counter
   post.update(comments_counter: post.comments.count)
end
```

2022-07-06 21:02 UTC, Gambit142 commented on app/models/post.rb
> +
- [x] [Optional] It would be nice to make this a private method and then, you use the Rails Active Callback method after_save to automatically call the method. If you decide to implement it, it would be like this:

```ruby on rails
...

after_save :update_post_counter

private

def update_post_counter
   post.update(comments_counter: post.comments.count)
end
```

2022-07-06 21:11 UTC, jsug9 commented
Dear @Gambit142 thank you so much for your feedback, it has been very helpful.

2022-07-06 21:16 UTC, EricMbouwe approved these changes
Hi @jsug9, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good PR
- Good job making the changes suggested in the previous review
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-06 21:17 UTC, merged

2022-07-06 23:18 UTC, Gambit142 commented
@jsug9 , I am glad I could be of help

2022-07-07 00:27 UTC, jsug9 commented
@Gambit142 your tip for "after_save" was awesome! And I liked that you showed the way to implement it. You are a great reviewer, keep up the good work!